version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws sts get-caller-identity
      - mkdir ~/.aws/ && touch ~/.aws/config
      - echo "[profile buildprofile]" > ~/.aws/config
      - echo "role_arn = arn:aws:iam::850441520537:role/Secretassumerole" >> ~/.aws/config
      - echo "credential_source = EcsContainer" >> ~/.aws/config
      - VUE_APP_STRIPE_KEY=$(aws secretsmanager get-secret-value --secret-id stripe-credentials --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .stripekey)
      - VUE_APP_API_URL=$(aws secretsmanager get-secret-value --secret-id app-api-url --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .apiurl)
      - VUE_APP_HCAPTCHA_SITE_KEY=$(aws secretsmanager get-secret-value --secret-id hcaptcha-credentials --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .hcaptchasitekey)
      - VUE_APP_HCAPTCHA_SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id hcaptcha-credentials --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .hcaptchasecretkey)
      - VUE_APP_TERMS_LINK=$(aws secretsmanager get-secret-value --secret-id mix-terms-privacy --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .mixterms)
      - VUE_APP_PRIVACY_LINK=$(aws secretsmanager get-secret-value --secret-id mix-terms-privacy --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .mixprivacy)
      - VUE_APP_GA_KEY=$(aws secretsmanager get-secret-value --secret-id ga-key --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .appgakey)
      - VUE_APP_GOOGLE_PLAY_URL=$(aws secretsmanager get-secret-value --secret-id google-apple-urls --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .googleplay)
      - VUE_APP_APPLE_STORE_URL=$(aws secretsmanager get-secret-value --secret-id google-apple-urls --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .applestore)
      - VUE_APP_AWS_RUM_ARN=$(aws secretsmanager get-secret-value --secret-id frontend-rum --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .arn)
      - VUE_APP_AWS_RUM_POOL_ID=$(aws secretsmanager get-secret-value --secret-id frontend-rum --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .pool)
      - VUE_APP_AWS_RUM_ENDPOINT=$(aws secretsmanager get-secret-value --secret-id frontend-rum --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .endpoint)
      - VUE_APP_AWS_RUM_APPLICATION_ID=$(aws secretsmanager get-secret-value --secret-id frontend-rum --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .id)
      - VUE_APP_ENV=$(aws secretsmanager get-secret-value --secret-id frontend-app-env --region us-east-1 --profile buildprofile | jq --raw-output '.SecretString' | jq -r .appenv)

  pre_build:
    commands:
      - AccountID=$(aws sts get-caller-identity --query Account --output text)
      - CommitID="$(echo $GitCommitID | head -c 8)"
      - $(aws ecr get-login --registry-ids $AccountID --no-include-email --region ${AWS_DEFAULT_REGION})
      - REPO_URI="$AccountID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$ServiceName"
      - REPOSITORY_URI="$REPO_URI-$BranchName"
  build:
    commands:
        - DOCKER_BUILDKIT=0 docker build -f script/dev/docker/Dockerfile --build-arg VUE_APP_ENV=$VUE_APP_ENV --build-arg VUE_APP_AWS_RUM_APPLICATION_ID=$VUE_APP_AWS_RUM_APPLICATION_ID --build-arg VUE_APP_AWS_RUM_ENDPOINT=$VUE_APP_AWS_RUM_ENDPOINT --build-arg VUE_APP_AWS_RUM_POOL_ID=$VUE_APP_AWS_RUM_POOL_ID --build-arg VUE_APP_AWS_RUM_ARN=$VUE_APP_AWS_RUM_ARN --build-arg VUE_APP_GOOGLE_PLAY_URL=$VUE_APP_GOOGLE_PLAY_URL --build-arg VUE_APP_APPLE_STORE_URL=$VUE_APP_APPLE_STORE_URL --build-arg VUE_APP_GA_KEY=$VUE_APP_GA_KEY --build-arg VUE_APP_STRIPE_KEY=$VUE_APP_STRIPE_KEY --build-arg VUE_APP_HCAPTCHA_SITE_KEY=$VUE_APP_HCAPTCHA_SITE_KEY --build-arg VUE_APP_HCAPTCHA_SECRET_KEY=$VUE_APP_HCAPTCHA_SECRET_KEY --build-arg VUE_APP_TERMS_LINK=$VUE_APP_TERMS_LINK --build-arg VUE_APP_PRIVACY_LINK=$VUE_APP_PRIVACY_LINK --build-arg VUE_APP_API_URL=$VUE_APP_API_URL -t ${REPOSITORY_URI}:${CommitID} .
        - docker tag ${REPOSITORY_URI}:${CommitID} ${REPOSITORY_URI}:latest
  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:${CommitID}
      - docker push ${REPOSITORY_URI}:latest
      - printf '[{"name":"task-%s","imageUri":"%s:%s"}]' "$ServiceName-$BranchName" "$REPOSITORY_URI" "$CommitID" > taskdef.json
artifacts:
  files: taskdef.json
